FROM node:alpine AS base
WORKDIR /srv
COPY package.json /srv/
RUN npm install -y

FROM node:alpine AS app
WORKDIR /srv
COPY --from=base /srv/node_modules ./node_modules
COPY --from=base /srv/package.json ./package.json
COPY src ./src
ENTRYPOINT [ "npm", "start" ]